#!/bin/bash

OS=""
ARCH=""

REBOOT_AFTER="false"
INSTANCE_SUPPORT="false"
CORE_FILE=""

NODE_INSTALLED="false"
NODE_VERSION=""
NODE_TARGET=""
NODE_PREFIX=""

NPM_INSTALLED="false"
NPM_VERSION=""
NPM_TARGET=""
NPM_PREFIX=""

HOOBS_INSTALLED="false"
UI_X_INSTALLED="false"
SELINUX_INSTALLED="false"
PACKAGE_MNGR=""

usage()
{
    echo ""
    echo "help: install [-r | --reboot] [-i | --instance] [-n | --node version]"
    echo "    Display information about builtin commands."
    echo ""
    echo "    Installs HOOBS with prerequisites, including Node, NPM and Avachi."
    echo "    This script allows you to adjust the version of Node, using the"
    echo "    -n (or --node) flag. It also allows you to adjust the version of"
    echo "    NPM using -m (or --npm) flag."
    echo ""
    echo "    Note:"
    echo "        This script requires elevated permissions, please run this with"
    echo "        SUDO or ROOT privileges."
    echo ""
    echo "    Options:"
    echo "        -r, --reboot              reboots after install"
    echo "        -i, --instance            install for instances"
    echo "        -n, --node [version]      the desired Node version"
    echo "        -m, --npm [version]       the desired NPM version"
    echo "        -c, --core [file]         file path to NPM pack file"
    echo "        --reset                   resets to factory settings"
    echo "        -h, --help                displays this help menu"
    echo ""
    echo "    Returns:"
    echo "        Returns success unless the install fails."
    echo ""
}

reset()
{
    echo ""
    echo "Reseting device"
    echo ""

    rm -fR /home/hoobs/.hoobs/
    shutdown -r now
}

get_os()
{
    OS=$(uname)
    ARCH=$(uname -m)
}

get_node()
{
    if command -v node > /dev/null; then
        NODE_INSTALLED="true"
        NODE_VERSION=$(node -v)
        NODE_VERSION=${NODE_VERSION#"v"}

        IFS=':'

        read -ra ADDR <<< "$PATH"

        for DIR in "${ADDR[@]}";
        do
            if [[ -f "$DIR/node" ]]; then
                NODE_PREFIX=$(cd $DIR/../;pwd)

                break
            fi
        done

        IFS=' '
    else
        NODE_INSTALLED="false"
        NODE_VERSION=""
        NODE_PREFIX=""
    fi
}

get_npm()
{
    if command -v npm > /dev/null; then
        NPM_INSTALLED="true"
        NPM_VERSION=$(npm -v)
        NPM_PREFIX=$(npm get prefix)
    else
        NPM_INSTALLED="false"
        NPM_VERSION=""
        NPM_PREFIX=""
    fi
}

get_package_manager()
{
    if command -v yum > /dev/null; then
        PACKAGE_MNGR="yum"
    elif command -v dnf > /dev/null; then
        PACKAGE_MNGR="dnf"
    elif command -v apt-get > /dev/null; then
        PACKAGE_MNGR="apt"
    fi
}

check_existing_install()
{
    if command -v hoobs > /dev/null; then
        HOOBS_INSTALLED="true"
    else
        HOOBS_INSTALLED="false"
    fi

    if command -v homebridge-config-ui-x > /dev/null; then
        UI_X_INSTALLED="true"
    else
        UI_X_INSTALLED="false"
    fi

    if command -v setsebool > /dev/null; then
        SELINUX_INSTALLED="true"
    else
        SELINUX_INSTALLED="false"
    fi
}

install_prequsits()
{
    get_package_manager

    case $PACKAGE_MNGR in
        "yum")
            yum install -y curl tar git policycoreutils
            ;;

        "dnf")
            dnf install -y curl tar git policycoreutils
            ;;

        "apt")
            apt-get update
            apt-get install -y curl tar git
            ;;
    esac

    if [ "$SELINUX_INSTALLED" = "true" ]; then
        setsebool -P httpd_can_network_connect 1
    fi
}

install_node_prequsits()
{
    get_node
    get_package_manager

    case $PACKAGE_MNGR in
        "yum")
            yum install -y python make gcc gcc-c++
            ;;

        "dnf")
            dnf install -y python make gcc gcc-c++
            ;;

        "apt")
            apt-get install -y python make gcc g++
            ;;
    esac

    if [[ "$NODE_INSTALLED" = "false" ]]; then
        case $PACKAGE_MNGR in
            "yum")
                yum install -y nodejs
                ;;

            "dnf")
                dnf install -y nodejs
                ;;

            "apt")
                apt-get install -y nodejs npm
                ;;
        esac
    fi
}

install_node()
{
    export npm_config_loglevel=error

    get_os
    get_node
    get_npm

    if [ "$NODE_INSTALLED" = "true" ]; then
        rm -f "$NODE_PREFIX/bin/node" > /dev/null 2>&1

        unlink "$NODE_PREFIX/bin/nodejs" > /dev/null 2>&1
        unlink "$NODE_PREFIX/bin/npm" > /dev/null 2>&1
        unlink "$NODE_PREFIX/bin/npx" > /dev/null 2>&1
    fi

    case $OS in
        "Linux")
            case $ARCH in
                "x86_64")
                    curl -k -O https://nodejs.org/dist/v$NODE_TARGET/node-v$NODE_TARGET-linux-x64.tar.gz
                    tar -xzf ./node-v$NODE_TARGET-linux-x64.tar.gz -C $NODE_PREFIX --strip-components=1 --no-same-owner > /dev/null 2>&1
                    rm -f ./node-v$NODE_TARGET-linux-x64.tar.gz > /dev/null 2>&1

                    npm config set -g prefix $NPM_PREFIX
                    npm install -g npm@$NPM_TARGET
                    npm config set -g prefix $NPM_PREFIX
                    ;;

                "armv6l")
                    curl -k -O https://nodejs.org/dist/v$NODE_TARGET/node-v$NODE_TARGET-linux-armv6l.tar.gz
                    tar -xzf ./node-v$NODE_TARGET-linux-armv7l.tar.gz -C $NODE_PREFIX --strip-components=1 --no-same-owner > /dev/null 2>&1
                    rm -f ./node-v$NODE_TARGET-linux-armv7l.tar.gz > /dev/null 2>&1

                    npm config set -g prefix $NPM_PREFIX
                    npm install -g npm@$NPM_TARGET
                    npm config set -g prefix $NPM_PREFIX
                    ;;

                "armv7l")
                    curl -k -O https://nodejs.org/dist/v$NODE_TARGET/node-v$NODE_TARGET-linux-armv7l.tar.gz
                    tar -xzf ./node-v$NODE_TARGET-linux-armv7l.tar.gz -C $NODE_PREFIX --strip-components=1 --no-same-owner > /dev/null 2>&1
                    rm -f ./node-v$NODE_TARGET-linux-armv7l.tar.gz > /dev/null 2>&1

                    npm config set -g prefix $NPM_PREFIX
                    npm install -g npm@$NPM_TARGET
                    npm config set -g prefix $NPM_PREFIX
                    ;;

                "armv8l")
                    curl -k -O https://nodejs.org/dist/v$NODE_TARGET/node-v$NODE_TARGET-linux-arm64.tar.gz
                    tar -xzf ./node-v$NODE_TARGET-linux-arm64.tar.gz -C $NODE_PREFIX --strip-components=1 --no-same-owner > /dev/null 2>&1
                    rm -f ./node-v$NODE_TARGET-linux-arm64.tar.gz > /dev/null 2>&1

                    npm config set -g prefix $NPM_PREFIX
                    npm install -g npm@$NPM_TARGET
                    npm config set -g prefix $NPM_PREFIX
                    ;;
            esac
            ;;

        "Darwin")
            curl -k -O https://nodejs.org/dist/v$NODE_TARGET/node-v$NODE_TARGET-darwin-x64.tar.gz
            tar -xzf ./node-v$NODE_TARGET-linux-x64.tar.gz -C $NODE_PREFIX --strip-components=1 --no-same-owner > /dev/null 2>&1
            rm -f ./node-v$NODE_TARGET-linux-x64.tar.gz > /dev/null 2>&1

            npm config set -g prefix $NPM_PREFIX
            npm install -g npm@$NPM_TARGET
            npm config set -g prefix $NPM_PREFIX
            ;;
    esac
}

install_npm()
{
    get_npm

    if [[ "$NPM_INSTALLED" = "false" ]]; then
        if [[ "$NPM_TARGET" == "" ]]; then
            NPM_TARGET="latest"
        fi

        npm install -g npm@$NPM_TARGET
    fi
}

clear_npm_cache()
{
    get_npm

    if [[ "$NPM_INSTALLED" = "true" ]]; then
        npm cache clean --force > /dev/null 2>&1
    fi
}

if [ "$(id -u)" != "0" ]; then
	usage
	exit
fi

while [ "$1" != "" ]; do
    case $1 in
        -r | --reboot )   REBOOT_AFTER="true"
                          ;;

        -i | --instance ) INSTANCE_SUPPORT="true"
                          ;;

        reset )           reset
                          exit
                          ;;

        -n | --node )     shift
                          NODE_TARGET=$1

                          if [[ "$NODE_TARGET" == "stable" ]]; then
                              NODE_TARGET="10.17.0"
                          elif [[ "$NODE_TARGET" == "lts" ]]; then
                              NODE_TARGET="12.14.0"
                          elif [[ "$NODE_TARGET" == "latest" ]]; then
                              NODE_TARGET="13.5.0"
                          fi

                          ;;

        -m | --npm )      shift
                          NPM_TARGET=$1

                          if [[ "$NODE_TARGET" == "stable" || "$NODE_TARGET" == "lts" ]]; then
                              NODE_TARGET="latest"
                          fi

                          ;;

        -c | --core )     shift
                          CORE_FILE=$1
                          ;;

        -h | --help )     usage
                          exit
                          ;;

        * )               usage
                          exit
    esac

    shift
done

get_os
get_node
get_npm
get_package_manager
check_existing_install

echo ""
echo "Thank You for choosing HOOBS"
echo "---------------------------------------------------------"

if [[ "$NODE_INSTALLED" = "true" ]]; then
    echo "Node Version $NODE_VERSION"
elif [[ "$OS" == "Darwin" ]]; then
    echo "Can Not Install Node"
    echo "------------------------------------------------------------"
    echo "Please go to https://nodejs.org/ and download and install   "
    echo "Node for macOS.                                             "
    echo "------------------------------------------------------------"

    exit
elif [[ "$NODE_TARGET" == "" ]]; then
    NODE_TARGET="10.17.0"
    NPM_TARGET="6.11.3"
fi

echo "Updating Repositories"

install_prequsits

if [[ "$NODE_INSTALLED" = "false" || ( "$NODE_TARGET" != "" && "$NODE_VERSION" != "$NODE_TARGET" ) ]]; then
    if [[ "$ARCH" == "armv6l" && "$NODE_TARGET" > "10.17.0" ]]; then
        echo "Can Not Install Node"
        echo "------------------------------------------------------------"
        echo "Node $NODE_VERSION is not supported on your system."
        echo "------------------------------------------------------------"
    fi

    echo "Installing Node"

    install_node_prequsits
    install_node
    get_node
    get_npm

    echo "Node $NODE_VERSION Installed"
fi

if [[ "$NPM_TARGET" != "" && "$NPM_VERSION" != "$NPM_TARGET" ]]; then
    install_npm
    get_npm

    echo "NPM $NPM_VERSION Installed"
fi

clear_npm_cache

if [[ "$UI_X_INSTALLED" = "true" ]]; then
    npm uninstall -g homebridge-config-ui-x
    npm install -g --unsafe-perm homebridge-config-ui-x
fi

if [[ "$HOOBS_INSTALLED" = "true" ]]; then
    npm uninstall -g @hoobs/hoobs

    if [[ "$CORE_FILE" != "" ]]; then
        npm install -g --unsafe-perm "$CORE_FILE"
    else
        npm install -g --unsafe-perm @hoobs/hoobs
    fi

    for f in /home/*;
    do 
        [ -d "$f/.hoobs/dist" ] && rm -fR $f/.hoobs/dist
        [ -d "$f/.hoobs/lib" ] && rm -fR $f/.hoobs/lib
    done;

    [ -d "/root/.hoobs/dist" ] && rm -fR /root/.hoobs/dist
    [ -d "/root/.hoobs/lib" ] && rm -fR /root/.hoobs/lib

    [ -d "/var/root/.hoobs/dist" ] && rm -fR /var/root/.hoobs/dist
    [ -d "/var/root/.hoobs/lib" ] && rm -fR /var/root/.hoobs/lib

    if [[ "$OS" != "Darwin" ]]; then
        if command -v hoobs > /dev/null; then
            echo ""
            echo "Restart HOOBS"
            echo "---------------------------------------------------------"

            hoobs switch hoobs
            hoobs service restart

            if [[ "$REBOOT_AFTER" = "true" ]]; then
                shutdown -r now
            fi
        fi
    fi
else
    if [[ "$CORE_FILE" != "" ]]; then
        npm install -g --unsafe-perm "$CORE_FILE"
    else
        npm install -g --unsafe-perm @hoobs/hoobs
    fi

    if [[ "$INSTANCE_SUPPORT" == "false" && "$OS" != "Darwin" ]]; then
        if command -v hoobs > /dev/null; then
            echo ""
            echo "Initializing HOOBS"
            echo "---------------------------------------------------------"

            if [[ "$REBOOT_AFTER" = "true" ]]; then
                hoobs service install --reboot
            else
                hoobs service install
            fi

            if [[ "$REBOOT_AFTER" = "true" ]]; then
                shutdown -r now
            fi
        fi
    fi
fi
