#!/bin/bash

OS=""
ARCH=""
PACKAGE_MNGR=""

get_os()
{
    OS=$(uname)
    ARCH=$(uname -m)
}

get_package_manager()
{
    if command -v yum > /dev/null; then
        PACKAGE_MNGR="yum"
    elif command -v dnf > /dev/null; then
        PACKAGE_MNGR="dnf"
    elif command -v apt-get > /dev/null; then
        PACKAGE_MNGR="apt"
    fi
}

if [ "$(id -u)" != "0" ]; then
	echo "This script needs to be ran with elevated permissons (sudo)"
	exit
fi

get_os
get_package_manager

if [[ "$OS" != "Linux" || "$ARCH" != "armv7l" || "$PACKAGE_MNGR" != "apt" ]]; then
    echo "This version of FFMPEG can not be installed on this device"
    exit
fi

apt-get update	
apt-get install -y libtool libx264-dev

echo "Installing FFMPEG"

curl -ssl -O https://github.com/hoobs-org/hoobs-gen/raw/master/stage4/00-ffmeg/files/ffmpeg.tar.gz
tar -xzf ./ffmpeg.tar.gz -C /usr/local --strip-components=1 --no-same-owner > /dev/null 2>&1
rm -f ./ffmpeg.tar.gz > /dev/null 2>&1

echo "Configuring"

libtool --finish /usr/local/lib
ldconfig -n /usr/local/lib

echo "FFMPEG is installed"
