/**************************************************************************************************
 * hoobs-core                                                                                     *
 * Copyright (C) 2020 HOOBS                                                                       *
 *                                                                                                *
 * This program is free software: you can redistribute it and/or modify                           *
 * it under the terms of the GNU General Public License as published by                           *
 * the Free Software Foundation, either version 3 of the License, or                              *
 * (at your option) any later version.                                                            *
 *                                                                                                *
 * This program is distributed in the hope that it will be useful,                                *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of                                 *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                                  *
 * GNU General Public License for more details.                                                   *
 *                                                                                                *
 * You should have received a copy of the GNU General Public License                              *
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.                          *
 **************************************************************************************************/

exports.services = {
    "3E": "accessory_information",
    "BB": "air_purifier",
    "8D": "air_quality_sensor",
    "96": "battery",
    "110": "camera_rtp_stream_management",
    "97": "carbon_dioxide_sensor",
    "7F": "carbon_monoxide_sensor",
    "80": "contact_sensor",
    "81": "door",
    "121": "doorbell",
    "40": "fan",
    "B7": "fan",
    "BA": "filter_maintenance",
    "D7": "faucet",
    "41": "garage_door_opener",
    "BC": "heater_cooler",
    "BD": "humidifier_dehumidifier",
    "82": "humidity_sensor",
    "CF": "irrigation_system",
    "83": "leak_sensor",
    "84": "light_sensor",
    "43": "lightbulb",
    "44": "lock_management",
    "45": "lock_mechanism",
    "112": "microphone",
    "85": "motion_sensor",
    "86": "occupancy_sensor",
    "47": "outlet",
    "7E": "security_system",
    "CC": "service_label",
    "B9": "slat",
    "87": "smoke_sensor",
    "113": "speaker",
    "89": "stateless_programmable_switch",
    "49": "switch",
    "8A": "temperature_sensor",
    "4A": "thermostat",
    "D0": "valve",
    "8B": "window",
    "8C": "window_covering",
    "D8": "television",
    "D9": "input_source",
    "113": "television_speaker"
};

exports.characteristics = {
    "A6": "accessory_flags",
    "B0": "active",
    "1": "administrator_only_access",
    "64": "air_particulate_density",
    "65": "air_particulate_size",
    "95": "air_quality",
    "5": "audio_feedback",
    "68": "battery_level",
    "8": "brightness",
    "92": "carbon_dioxide_detected",
    "93": "carbon_dioxide_level",
    "94": "carbon_dioxide_peak_level",
    "69": "carbon_monoxide_detected",
    "90": "carbon_monoxid_level",
    "91": "carbon_monoxide_peak_level",
    "8F": "charging_state",
    "CE": "color_temperature",
    "6A": "contact_sensor_state",
    "D": "cooling_threshold_temperature",
    "A9": "air_purifier_state",
    "6B": "ambient_light_level",
    "E": "door_state",
    "AF": "fan_state",
    "B1": "heater_cooler_state",
    "F": "heating_cooling_state",
    "6C": "horizontal_tilt_angle",
    "B3": "humidifier_dehumidifier_state",
    "6D": "position",
    "10": "relative_humidity",
    "AA": "slat_state",
    "11": "temperature",
    "C1": "tilt_angle",
    "6E": "vertical_tilt_angle",
    "11D": "digital_zoom",
    "AC": "filter_change_indication",
    "AB": "filter_life_level",
    "52": "firmware_revision",
    "53": "hardware_revision",
    "12": "heating_threshold_temperature",
    "6F": "hold_position",
    "13": "hue",
    "14": "identify",
    "11F": "image_mirroring",
    "11E": "image_rotation",
    "D2": "in_use",
    "D6": "is_configured",
    "70": "leak_detected",
    "19": "lock_control_point",
    "1D": "lock_current_state",
    "1C": "lock_last_known_action",
    "1A": "lock_management_auto_security_timeout",
    "A7": "lock_physical_controls",
    "1E": "lock_target_state",
    "1F": "logs",
    "20": "manufacturer",
    "21": "model",
    "22": "motion_detected",
    "11A": "mute",
    "23": "name",
    "11B": "night_vision",
    "C4": "nitrogen_dioxide_density",
    "24": "obstruction_detected",
    "71": "occupancy_detected",
    "25": "on",
    "11C": "optical_zoom",
    "26": "in_use",
    "C3": "ozone_density",
    "4C": "pair_setup",
    "4E": "pair_verify",
    "4F": "pairing_features",
    "50": "pairing_pairings",
    "C7": "pm_density",
    "C6": "pm_density",
    "72": "position_state",
    "D1": "program_mode",
    "73": "programmable_switch_event",
    "C9": "relative_humidity_dehumidifier_threshold",
    "CA": "relative_humidity_humidifier_threshold",
    "D4": "remaining_duration",
    "AD": "reset_filter_indication",
    "28": "rotation_direction",
    "29": "rotation_speed",
    "2F": "saturation",
    "8E": "security_system_alarm_type",
    "66": "security_system_current_state",
    "67": "security_system_target_state",
    "117": "selected_rtp_stream_configuration",
    "30": "serial_number",
    "CB": "service_label_index",
    "CD": "service_label_namespace",
    "D3": "set_duration",
    "118": "setup_endpoints",
    "C0": "slat_type",
    "76": "smoke_detected",
    "75": "status_active",
    "77": "status_fault",
    "78": "status_jammed",
    "79": "status_low_battery",
    "7A": "status_tampered",
    "120": "streaming_status",
    "C5": "sulphur_dioxide_density",
    "115": "supported_audio_stream_configuration",
    "116": "supported_rtp_configuration",
    "114": "supported_video_stream_configuration",
    "B6": "swing_mode",
    "A8": "target_air_purifier_state",
    "AE": "target_air_quality",
    "32": "target_door_state",
    "BF": "target_fan_state",
    "B2": "target_heater_cooler_state",
    "33": "target_heating_cooling_state",
    "7B": "target_horizontal_tilt_angle",
    "B4": "target_humidifier_dehumidifier_state",
    "7C": "target_position",
    "34": "target_relative_humidity",
    "BE": "target_slat_state",
    "35": "target_temperature",
    "C2": "target_tilt_angle",
    "7D": "target_vertical_tilt_angle",
    "36": "temperature_display_units",
    "D5": "valve_type",
    "37": "version",
    "C8": "voc_density",
    "119": "volume",
    "B5": "water_level",
    "E7": "active_identifier",
    "E3": "configured_name",
    "E8": "sleep_discovery_mode",
    "DD": "closed_captions",
    "136": "display_order",
    "E0": "current_media_state",
    "137": "target_media_state",
    "E2": "picture_mode",
    "DF": "power_mode_selection",
    "E1": "remote_key",
    "DB": "input_source_type",
    "DC": "input_device_type",
    "E6": "identifier",
    "135": "current_visibility_state",
    "134": "target_visibility_state",
    "E9": "volume_control_type",
    "EA": "volume_selector",
};
